seamstress/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views

urlpatterns = [
    path('', views.login_view, name="login"),
    path('shop/', include('shop.urls', namespace='shop')),
    path('admin/', admin.site.urls),
    
]

shop/urls.py
from django.urls import path
from shop import views


app_name = 'shop'

urlpatterns = [
    path('dashboard', views.Dashboard, name='dashboard'),
    path('newcustomer', views.Customers, name='newcustomer'),
    path('edit/customer/<str:pk>/', views.EditCustomers, name='editcustomer'),
    path('addmeasurement/<str:pk>/', views.Malemeasurement, name="addmeasurement"),
    path('addmeasurements/<str:pk>/', views.Femalemeasurement, name="addmeasurements"),
    path('customerOrder/<str:pk>/', views.customerOrder, name="customerOrder"),
    path('editorder/<str:pk>/', views.EditOrder, name="editorder"),
    path('customerprofile/<str:pk>/', views.customerord, name="customerprofile"),
    path('allorders', views.allorders, name="allorders"),
    path('createrevenue', views.create_revenue, name="createrevenue"),
    path('editrevenue/<str:pk>/', views.edit_revenue, name="editrevenue"),
    path('createexpenditure', views.create_exdenditure, name="createexpenditure"),
    path('ordersdue', views.orders_due, name="ordersdue"),
    path('delayedorders', views.delayed_orders, name="delayedorders"),
    path('accountreceivable', views.account_receivable, name="accountreceivable"),
    path('totalrevenue', views.allrevenue, name="totalrevenue"),
    path('totalexpense', views.allexpenses, name="totalexpense"),
    path('income&expenditure', views.income_expenditure, name="income&expenditure"),
    path('yearlyincome&expenditure', views.stats_income_expenditure,name="yearlyincome&expenditure"),
    path('montlyincome&expenditure', views.montlystats_income_expenditure,name="montlyincome&expenditure"), 
    path('logout', views.logout_request, name="logout"),
    path('signup', views.signup, name="signup"),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.conf import settings
from django.db.models import Sum
import datetime
from .utils import incrementor

# Create your models here.


class UserSession(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    session = models.OneToOneField(Session, on_delete=models.CASCADE)

# Create your models here.
class Customer(models.Model):
    gender = (
        ('Male', 'Male'),
        ('Female', 'Female')
    )
    id = models.CharField(max_length=200, primary_key=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    date_created = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=10, null=True, blank=True)
    gender = models.CharField(max_length=7, choices=gender)
    accross_back = models.CharField(max_length=10, null=True, blank=True)
    around_arm = models.CharField(max_length=10, null=True, blank=True)
    bust = models.CharField(max_length=10, null=True, blank=True)
    hips = models.CharField(max_length=10, null=True, blank=True)
    waist = models.CharField(max_length=10, null=True, blank=True)
    dress_lenght = models.CharField(max_length=10, null=True, blank=True)
    shoulder_to_under_bust = models.CharField(max_length=10,null=True, blank=True)
    upper_bust = models.CharField( max_length=10, null=True, blank=True)
    under_bust = models.CharField(max_length=10, null=True, blank=True)
    shoulder_to_waist = models.CharField(max_length=10, null=True, blank=True)
    s_n = models.CharField(max_length=10, null=True, blank=True)
    top_or_shirt_length = models.CharField(max_length=10,null=True, blank=True)
    skirt_or_trouser_length = models.CharField(max_length=10,null=True, blank=True)
    half_length = models.CharField(max_length=10, null=True, blank=True)
    chest = models.CharField(max_length=10, null=True, blank=True)
    sleeves = models.CharField(max_length=10, null=True, blank=True)
    thigh = models.CharField(max_length=10, null=True, blank=True)
    bar = models.CharField(max_length=10, null=True, blank=True)
    neck = models.CharField(max_length=10, null=True, blank=True)
    knee = models.CharField(max_length=10, null=True, blank=True)
    calf = models.CharField(max_length=10, null=True, blank=True)
    seat = models.CharField(max_length=10, null=True, blank=True)
      
    def __str__(self):
        return self.first_name + " " + self.last_name
    
    def save(self, *args, **kwargs):
        
        today = datetime.datetime.now()
        
        if not self.date_created:
            self.date_created = today
            
        if not self.id:
            number = incrementor()
            self.id = "CUS" + str(number())
            while Customer.objects.filter(id=self.id).exists():
                self.id = "CUS" + str(number())
        super(Customer, self).save(*args, **kwargs)
    


class Order(models.Model):
    status = (
        ('Pending', 'Pending'),
        ('Closed', 'Closed'),
    )
    id = models.CharField(max_length=100, primary_key=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    description = models.CharField(max_length=10, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    status = models.CharField(max_length=15,choices=status)
    order_date = models.DateField(null=True, blank=True)
    payment = (
        ('Part Payment', 'Part Payment'),
        ('Full Payment', 'Full Paument'),
        ('No Payment', 'No Payment'),
    )
    payments = models.CharField(max_length=15, choices=payment)
    closing_date = models.DateField(null=True, blank=True)
    
    def __str__(self):
        return self.id
       
    def save(self, *args, **kwargs):

        today = datetime.datetime.now()

        if not self.order_date:
            self.order_date = today
            
        if self.price == self.amount_paid:
            self.payments = 'Full Payment'
        elif self.amount_paid > 0 and self.amount_paid < self.price:
            self.payments = 'Part Payment'
        else:
            self.payments = 'No Payment'

        if not self.id:
            number = incrementor()
            self.id = "ORD" + str(number())
            while Order.objects.filter(id=self.id).exists():
                self.id = "ORD" + str(number())
        super(Order, self).save(*args, **kwargs)
    
    
    def total(self):
        sum = 0
        today = datetime.datetime.now()
        total_order = Order.objects.filter(balance__gt=0.00, order_date__year=today.year)
        for obj in total_order:
             sum += obj
        return sum
        

class Revenue(models.Model):
    code = (
        ('Orders', 'Orders'),
        ('Sales', 'Sales'),
    )
    id = models.CharField(max_length=100, primary_key=True)
    account_code = models.CharField(max_length=10, choices=code, default='Sales')
    amount = models.DecimalField( max_digits=10, decimal_places=2, default=0.00)
    orderno = models.CharField(max_length=100,null=True, blank=True)
    created_date = models.DateField()
    
    def __str__(self):
        return self.account_code + " " + str(self.amount)
    
    def save(self, *args, **kwargs):
        today = datetime.datetime.now()

        if not self.created_date:
            self.created_date = today
        
        if not self.id:
            number = incrementor()
            self.id = "REV" + str(number())
            while Revenue.objects.filter(id=self.id).exists():
                self.id = "REV" + str(number())
        super(Revenue, self).save(*args, **kwargs)


class Expenditure(models.Model):
    code = (
        ('T&T', 'T&T'),
        ('Salaries', 'Salaries'),
        ('Bills', 'Bills'),
    )
    id = models.CharField(max_length=100, primary_key=True)
    account_code = models.CharField(max_length=10, choices=code)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    created_date = models.DateField()

    def __str__(self):
        return self.account_code + " " + str(self.amount)

    def save(self, *args, **kwargs):
        today = datetime.datetime.now()

        if not self.created_date:
            self.created_date = today

        if not self.id:
            number = incrementor()
            self.id = "EXP" + str(number())
            while Expenditure.objects.filter(id=self.id).exists():
                self.id = "EXP" + str(number())
        super(Expenditure, self).save(*args, **kwargs)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, get_user_model
from .import models
from datetime import date


User = get_user_model()

class DateInput(forms.DateInput):
    input_type = 'date'


class CustomerForm(forms.ModelForm):
    
    class Meta():
        model = models.Customer
        fields = ('first_name', 'last_name','gender', 'location', 'phone')
        
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name...'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name...'}),
            'location': forms.TextInput(attrs={'placeholder': 'Location...'}),
            'phone': forms.TextInput(attrs={'placeholder': 'Mobile Number...'}),
        }
        
        labels ={
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'location': 'Location',
            'phone': 'Mobile No.'
        }
    

class FemaleMeasurementForm(forms.ModelForm):

    class Meta():
        model = models.Customer
        fields = ('accross_back', 'around_arm', 'bust',
                  'hips', 'waist', 'dress_lenght', 'shoulder_to_under_bust', 'upper_bust',
                  'under_bust', 'shoulder_to_waist', 's_n', 'top_or_shirt_length', 'skirt_or_trouser_length', 'half_length', 'sleeves', 'knee', 'thigh', 'seat')

        widgets = {
            'accross_back': forms.TextInput(attrs={'placeholder': 'AB...'}),
            'around_arm': forms.TextInput(attrs={'placeholder': 'Arm...'}),
            'bust': forms.TextInput(attrs={'placeholder': 'Bust...'}),
            'hips': forms.TextInput(attrs={'placeholder': 'Hips...'}),
            'upper_bust': forms.TextInput(attrs={'placeholder': 'Upper bust...'}),
            'under_bust': forms.TextInput(attrs={'placeholder': 'Under bust...'}),
            's_n': forms.TextInput(attrs={'placeholder': 'S-n...'}),
            'waist': forms.TextInput(attrs={'placeholder': 'Waist...'}),
            'dress_lenght': forms.TextInput(attrs={'placeholder': 'Dress Lenght...'}),
            'shoulder_to_under_bust': forms.TextInput(attrs={'placeholder': 'Shoulder To Under Bust...'}),
            'shoulder_to_waist': forms.TextInput(attrs={'placeholder': 'Sleeve To Waist...'}),
            'top_or_shirt_length': forms.TextInput(attrs={'placeholder': 'Blouse...'}),
            'skirt_or_trouser_length': forms.TextInput(attrs={'placeholder': 'Skirt Lenght...'}),
            'half_length': forms.TextInput(attrs={'placeholder': 'Half Lenght...'}),
            'sleeves': forms.TextInput(attrs={'placeholder': 'Sleeves...'}),
            'knee': forms.TextInput(attrs={'placeholder': 'Knee...'}),
            'thigh': forms.TextInput(attrs={'placeholder': 'Thigh...'}),
            'seat': forms.TextInput(attrs={'placeholder': 'Seat...'}),
            
        }

        labels = {
            'accross_back': 'Ab',
            'around_arm': 'Arm',
            'dress_lenght': 'Dress ',
            'shoulder_to_under_bust': 'S-ub',
            'shoulder_to_waist': 'Sleeve To Waist',
            'top_or_shirt_length': 'Blouse',
            'skirt_or_trouser_length': 'Skirt ',
            
        }


class MaleMeasurementForm(forms.ModelForm):
    
    class Meta():
        model = models.Customer
        fields = ('accross_back', 'around_arm',
                  'hips', 'waist', 'top_or_shirt_length', 'skirt_or_trouser_length',
                  'chest', 'sleeves', 'thigh','bar','neck','knee','calf'
                  
                   )

        widgets = {
            'accross_back': forms.TextInput(attrs={'placeholder': 'A b...'}),
            'around_arm': forms.TextInput(attrs={'placeholder': 'Arm...'}),
            'hips': forms.TextInput(attrs={'placeholder': 'Hips...'}),
            'waist': forms.TextInput(attrs={'placeholder': 'Waist...'}),
            'top_or_shirt_length': forms.TextInput(attrs={'placeholder': 'Shirt Lenght...'}),
            'skirt_or_trouser_length': forms.TextInput(attrs={'placeholder': 'Trouser Lenght...'}),
            'chest': forms.TextInput(attrs={'placeholder': 'Chest...'}),
            'sleeves': forms.TextInput(attrs={'placeholder': 'Sleeves...'}),
            'neck': forms.TextInput(attrs={'placeholder': 'Neck...'}),
            'thigh': forms.TextInput(attrs={'placeholder': 'Thigh...'}),
            'bar': forms.TextInput(attrs={'placeholder': 'Bar...'}),
            'knee': forms.TextInput(attrs={'placeholder': 'Knee...'}),
            'calf': forms.TextInput(attrs={'placeholder': 'Calf...'}),
        }

        labels = {
            'accross_back': 'Ab',
            'around_arm': 'Arm',
            'top_or_shirt_length': 'Top to lenght',
            'skirt_or_trouser_length': 'Trouser Length',          
        }


class OrderForm(forms.ModelForm):

    class Meta():
        model = models.Order
        fields = ('price', 'amount_paid', 'balance',
                  'closing_date', 'description')
    
        widgets = {
            'price': forms.TextInput(attrs={'placeholder': 'price...'}),
            'amount_paid': forms.TextInput(attrs={'placeholder': 'Amount Paid...'}),
            'balance': forms.TextInput(attrs={'placeholder': 'Balance...'}),
            'closing_date': DateInput(),
            'description': forms.TextInput(attrs={'placeholder': 'Description'})
        }
        labels = {
            'description': 'Job Description',
            
        }

class EditOrderForm(forms.ModelForm):
    
    class Meta():
        model = models.Order
        fields = ('price', 'amount_paid', 'balance', 'status', 'closing_date', 'description')

        widgets = {
            'price': forms.TextInput(attrs={'placeholder': 'price...'}),
            'amount_paid': forms.TextInput(attrs={'placeholder': 'Amount Paid...'}),
            'balance': forms.TextInput(attrs={'placeholder': 'Balance...'}),
            'closing_date': DateInput(),
            'description': forms.TextInput(attrs={'placeholder': 'Description'})
        }
        labels = {
            'description': 'Job Description',

        }


class ExpenditureForm(forms.ModelForm):

    class Meta():
        model = models.Expenditure
        fields = ('account_code', 'amount')

        widgets = {
            'amount': forms.TextInput(attrs={'placeholder': 'Amount ...'}),
        }
        
        labels = {
            'account_code': 'Accounts Code',
            'amount': 'Amount',
        }


class RevenueForm(forms.ModelForm):
    
    class Meta():
        model = models.Revenue
        fields = ('account_code', 'amount')

        widgets = {
            'amount': forms.TextInput(attrs={'placeholder': 'Amount ...'}),
        }
        
        labels = {
            'account_code': 'Accounts Code  (Orders is not acceptable)',
            'amount': 'Amount',
        }


class UserLoginForm(forms.Form):
    username = forms.CharField(label=False, widget=forms.TextInput(
        attrs={'placeholder': 'Username'}))
    password = forms.CharField(label=False, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('Username or Password incorrect')
            if not user.check_password(password):
                raise forms.ValidationError('Username or Password incorrect')
            if not user.is_active:
                raise forms.ValidationError('Username or Password incorrect')
        return super(UserLoginForm, self).clean(*args, **kwargs)

    class Meta():
        model = models.User
        fields = ('username', 'password')


class CreateUserForm(UserCreationForm):
    username = forms.CharField(label=False, widget=forms.TextInput(
        attrs={'placeholder': 'Username'}))
    first_name = forms.CharField(label=False, widget=forms.TextInput(
        attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(label=False, widget=forms.TextInput(
        attrs={'placeholder': 'Last Name'}))
    email = forms.EmailField(label=False, widget=forms.TextInput(
        attrs={'placeholder': 'Email'}))
    password1 = forms.CharField(label=False, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(label=False, widget=forms.PasswordInput(
        attrs={'placeholder': 'Comfirm Password'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name',
                  'email', 'password1', 'password2']

templates/shop/base2.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- data tabele -->
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                   {% block content%} 
                  
                    
                   {% endblock %}
                    
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->
        {% include "shop/footer.html" %}

    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/jquery/jquery.min.map' %}"></script>
    <script src="{% static 'plugins/jquery/jquery.slim.js' %}"></script>
    <script src="{% static 'plugins/jquery/jquery.slim.min.js' %}"></script>
    <script src="{% static 'plugins/jquery/jquery.slim.min.map' %}"></script>
    <script src="{% static 'plugins/jquery/jquery.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- DataTables  & Plugins -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": [ "csv", "excel", "pdf", "print"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "order": [0, 'desc'],
                "info": true,
                "autoWidth": false,
                "responsive": true,
                "buttons": ["csv", "excel", "pdf", "print"]
            }).buttons().container().appendTo('#example2_wrapper .col-md-6:eq(0)');
        });
    </script>
    {% comment %} JQUERY code to calculate Net_amount {% endcomment %}
    <script>
        $(document).ready(function () {

            $("#id_price").keyup(function () {
                total = $("#id_price").val() - $("#id_amount_paid").val();
                $("#id_balance").val(total.toFixed(2));
            });
            $("#id_amount_paid").keyup(function () {
                total = $("#id_price").val() - $("#id_amount_paid").val();
                $("#id_balance").val(total.toFixed(2));
            });
            $("#id_balance").keyup(function () {
                total = $("#id_price").val() - $("#id_amount_paid").val();
                $("#id_balance").val(total.toFixed(2));
            });
        });
    </script>
</body>

</html>

templates/shop/expenses.html
{% extends "shop/base.html" %}
 {% load crispy_forms_tags %}
  {% block content%}
 <div class="row">
    <div class="col-10 mx-auto">
    
        <!-- Main content -->
        <div class="content ">
            <div class="container-fluid">
                <div class="row ">
                    <div class="col-lg">
                        <div class="card ">
                            <div class="card-header bg-pink color-palette">
                                <h3 class="card-title">Add Expenditure</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" method="POST">
                                {% csrf_token %}
                                <div class="card-body">
                                    <div class="row">
                                        <div class="form-group col">
                                            {{ form.account_code|as_crispy_field }}
                                        </div>
                                        <div class="form-group col">
                                            {{ form.amount|as_crispy_field }}
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="submit" class="btn bg-pink color-palette">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
   
 </div>

    
    {% endblock %}
  

templates/shop/footer.html
<!-- Main Footer -->
<footer class="main-footer">

    <!-- Default to the left -->
    <strong >Copyright &copy; 2021 </strong>
    
</footer>

templates/shop/navbar.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- user details -->
        <li class="nav-item dropdown open float-right">
            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <span class=" hello-msg"><b>{{request.user.first_name}} {{request.user.last_name}}</b></span>
            </a>
            <ul class="dropdown-menu dropdown-usermenu pull-left">
                <li>
                   
                    <a class="dropdown-item" href="{% url 'shop:logout' %}"><i class="fa fa-sign-out pull-right"></i> Log
                        Out</a>
                </li>
            </ul>
        </li>
    </ul>
</nav>

templates/shop/sidebar.html
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <span class="brand-text font-weight-light"><b>Premium</b> TAILORING</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-5">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Menu
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'shop:dashboard' %}" class="nav-link">
                                <i class="fas fa-home nav-icon"></i>
                                <p>Dashboard</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'shop:newcustomer' %}" class="nav-link">
                                <i class="fas fa-users nav-icon"></i>
                                <p>Add Customer</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'shop:createrevenue' %}" class="nav-link">
                                <i class="fas fa-money-bill-wave-alt nav-icon"></i>
                                <p>Add Revenue</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'shop:createexpenditure' %}" class="nav-link">
                                <i class="fas fa-chart-line nav-icon"></i>
                                <p>Add Expenditure</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-table"></i>
                        <p>
                            Reports
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'shop:allorders' %}" class="nav-link">
                                <i class="fas fa-anchor"></i>
                                <p> All Orders</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'shop:ordersdue' %}" class="nav-link">
                                <i class="fas fa-anchor"></i>
                                <p> Orders Due</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'shop:delayedorders' %}" class="nav-link">
                                <i class="fas fa-anchor"></i>
                                <p> Delayed Orders</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'shop:accountreceivable' %}" class="nav-link">
                                <i class="fas fa-dollar-sign"></i>
                                <p>  Account Receivable</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'shop:totalrevenue' %}" class="nav-link">
                                <i class="fas fa-dollar-sign"></i>
                                <p> Total Revenue</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'shop:totalexpense' %}" class="nav-link">
                                <i class="fas fa-dollar-sign"></i>
                                <p> Total Expenditure</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'shop:income&expenditure' %}" class="nav-link">
                                <i class="fas fa-Euro-sign"></i>
                                <p>Income & Expenditure</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'shop:montlyincome&expenditure' %}" class="nav-link">
                                <i class="fas fa-Euro-sign"></i>
                                <p>Summary Income & Expenditure</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>